### ISSUE TITLE
Segfault in host_save after resolving an IP with an illegal PTR record.

### ISSUE THREAD

**Issue by CyberLeo** [protomuck/protomuck#10]
hostdb->name ends up a null pointer when an IP is resolved to an illegal PTR.

```
(gdb) bt
#0  0x0000000801a109ba in thr_kill () from /lib/libc.so.7
#1  0x0000000801a10984 in __raise (s=6) at /srv/builder/cdnjail-11-amd64/src/lib/libc/gen/raise.c:52
#2  0x0000000801a108f9 in abort () at /srv/builder/cdnjail-11-amd64/src/lib/libc/stdlib/abort.c:65
#3  0x0000000000421e5f in panic (message=<value optimized out>) at game.c:429
#4  0x00000000004e6aba in bailout (sig=0) at signal.c:207
#5  0x0000000801d12cf0 in handle_signal (actp=0x7ffffffbd940, sig=11, info=0x7ffffffbdd30, ucp=0x7ffffffbd9c0) at /srv/builder/cdnjail-11-amd64/src/lib/libthr/thread/thr_sig.c:246
#6  0x0000000801d122bf in thr_sighandler (sig=11, info=0x7ffffffbdd30, _ucp=0x7ffffffbd9c0) at /srv/builder/cdnjail-11-amd64/src/lib/libthr/thread/thr_sig.c:189
#7  <signal handler called>
#8  0x0000000801a8e6cc in strcmp () from /lib/libc.so.7
#9  0x0000000000503a66 in host_save () at netresolve.c:976
#10 0x0000000000420ecb in check_dump_time () at events.c:75
#11 0x000000000042148e in next_muckevent () at events.c:304
#12 0x000000000050d33e in shovechars () at interface.c:1926
#13 0x000000000050cd24 in main (argc=<value optimized out>, argv=<value optimized out>) at interface.c:779
```
```
(gdb) print hostdb
$3 = (struct hostinfo *) 0x8055f94a8
(gdb) print hostdb->name
$4 = 0x0
(gdb) print hostdb->wupd
$5 = 1571563419
(gdb) print hostdb->a   
$6 = 1841923428
```
IP is 109.201.133.100.

```
$ drill -t ptr 100.133.201.109.in-addr.arpa
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 63452
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 3 
;; QUESTION SECTION:
;; 100.133.201.109.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
100.133.201.109.in-addr.arpa.	81641	IN	PTR	.

;; AUTHORITY SECTION:
133.201.109.in-addr.arpa.	168040	IN	NS	ns3.nforce.com.
133.201.109.in-addr.arpa.	168040	IN	NS	ns2.dbn.nforce.nl.
133.201.109.in-addr.arpa.	168040	IN	NS	ns1.dbn.nforce.nl.

;; ADDITIONAL SECTION:
ns1.dbn.nforce.nl.	81640	IN	A	77.247.176.114
ns2.dbn.nforce.nl.	81640	IN	A	77.247.176.115
ns3.nforce.com.	81640	IN	A	85.159.238.17

;; Query time: 1 msec
;; SERVER: 10.4.4.16
;; WHEN: Sun Oct 20 06:42:58 2019
;; MSG SIZE  rcvd: 184
```

**Comment by CyberLeo** [comment]
Turns out I fixed this two years ago, but never merged the fix.
